---
platform: linux

inputs:
 - name: concourse-mgmt
 - name: concourse-team-configs

params:
  CONCOURSE_USERNAME:
  CONCOURSE_PASSWORD:
  CONCOURSE_URL:
  ENV:

run:
  dir: concourse-team-configs
  path: ../concourse-mgmt/tasks/set-team/task.sh
